# torchrun --nproc_per_node=2 train.py --config_path configs/local_sP_mN.yml --exp local_sP_mN --results_dir output/ --encoder_agg none --decoder_agg none
#单任务P
ST_Datasets:
  - dataname: pascalcontext
    local_epochs: 4
    tr_batch: 4
    val_batch: 4
    nworkers: 4
    optimizer: adamw
    lr: 0.0001
    weight_decay: 0.0001
    warmup_epochs: 5
    task_dict:
      semseg: 2
      human_parts: 2
      normals: 2
      edge: 2
      sal: 2

#多任务N
MT_Datasets:
  - dataname: nyud
    client_num: 2
    local_epochs: 4
    tr_batch: 4
    val_batch: 4
    nworkers: 4
    optimizer: adamw
    lr: 0.0001
    weight_decay: 0.0001
    warmup_epochs: 5
    task_dict:
      semseg: 1
      normals: 1
      edge: 1
      depth: 1
    
Model:
  backbone_type: swin-t
  backbone_pretrained: True

Hyperweight:
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9